config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "dashboard#home"

  post "robinhood_login", to: "robinhood#login"
  get "logout", to: "robinhood#logout"

  get "portfolios", to: "robinhood#portfolios"
  get "portfolio_history", to: "robinhood#portfolio_history"
  get "quote", to: "robinhood#quote"
  get "markets", to: "robinhood#markets"
  get "fundamentals", to: "robinhood#fundamentals"
  get "history", to: "robinhood#history"
  get "movers", to: "robinhood#movers"
  get "news", to: "robinhood#news"
  get "dividends", to: "robinhood#dividends"
  get "documents", to: "robinhood#documents"
  get "price_chart", to: "robinhood#price_chart"
  get "api", to: "robinhood#api"
  get "experiments", to: "robinhood#experiments"

  get "positions", to: "robinhood#positions"
  post "reorder_positions", to: "robinhood#reorder_positions"

  get "transfers", to: "robinhood#transfers"
  post "new_transfer", to: "robinhood#new_transfer"
  get "cancel_transfer", to: "robinhood#cancel_transfer"

  get "cards", to: "robinhood#cards"
  get "dismiss_card", to: "robinhood#dismiss_card"
  get "dismiss_all_cards", to: "robinhood#dismiss_all_cards"

  post "add_to_watchlist", to: "robinhood#add_to_watchlist"
  post "remove_from_watchlist", to: "robinhood#remove_from_watchlist"
  post "create_watchlist", to: "robinhood#create_watchlist"
  get "watchlist", to: "robinhood#watchlist"

  get "orders", to: "robinhood#orders"
  post "new_order", to: "robinhood#new_order"
  get "cancel_order", to: "robinhood#cancel_order"

  get "delete_stock_list", to: "robinhood#delete_stock_list"
  post "add_stock_list", to: "robinhood#add_stock_list"

  # crypto
  get "crypto_watchlist", to: "robinhood#crypto_watchlist"
end

app/views/layouts/_flash_message.html.haml
- %w[success info warning danger].each do |type|
  - if flash[type].present?
    .alert.alert-dismissible{role: "alert", class: "alert-#{type}"}
      %button.close{"data-dismiss": "alert", "aria-label": "Close"}
        %span{"aria-hidden": true} &times;
      %strong= flash[type]

app/views/layouts/_hash_display.html.haml
- if data.is_a?(Hash) && data["results"].present?
  - data = data["results"]
- if data.is_a? Array
  - data.each do |a|
    - a.each do |k,v|
      .col-xs-4.col-sm-3
        - if v =~ /http/
          = link_to k, api_path(url: v)
        - else
          #{k}: #{v}
        %br
- else
  - data.each do |k,v|
    .col-xs-4.col-sm-3
      - if v =~ /http/
        = link_to k, api_path(url: v)
      - else
        #{k}: #{v}
      %br

app/views/layouts/_robinhood_login_form.html.haml
.row
  .col-sm-6
    = form_tag robinhood_login_path, method: :post do
      .form-group
        = label_tag "Robinhood username"
        = text_field_tag :username, flash[:username], placeholder: "Robinhood username", class: "form-control", required: true, autofocus: true
      .form-group
        = label_tag "Password"
        = password_field_tag :password, flash[:password], placeholder: "Password", class: "form-control", required: true
      - if params["mfa_required"] == 'true'
        .form-group
          = label_tag "Security code"
          = text_field_tag :security_code, nil, placeholder: "Code", class: "form-control", required: true
      - if params["challenge_required"] == 'true'
        .form-group
          = label_tag "Security code"
          = text_field_tag :challenge_code, nil, placeholder: "Code", class: "form-control", required: true
      = submit_tag "Log in", class: "btn btn-default"

app/views/layouts/_side_menu.html.haml
- if user_logged_in_to_robinhood?
  .col-md-2.no-padding
    .side-menu
      .wrapper
        .logo
          = link_to root_path do
            = image_tag asset_path("robinhood_logo")
        .main-menu
          .col-xs-12.no-padding
            = render "robinhood/quote_form"
          .menu-item= link_to "Portfolio", root_path
          .menu-item= link_to "Notifications", cards_path
          .menu-item= link_to "Orders", orders_path
          .menu-item= link_to "Dividends", dividends_path
          .menu-item= link_to "Transfers", transfers_path
          .menu-item= link_to "API", api_path
          .menu-item= link_to "Log out", logout_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    = render "application/favicon"

    %title RobinhoodOnRails
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render "layouts/flash_message"
    = render "layouts/side_menu"
    = yield