config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "dashboard#home"

  post "robinhood_login", to: "robinhood#login"
  get "logout", to: "robinhood#logout"

  get "portfolios", to: "robinhood#portfolios"
  get "portfolio_history", to: "robinhood#portfolio_history"
  get "quote", to: "robinhood#quote"
  get "markets", to: "robinhood#markets"
  get "fundamentals", to: "robinhood#fundamentals"
  get "history", to: "robinhood#history"
  get "movers", to: "robinhood#movers"
  get "news", to: "robinhood#news"
  get "dividends", to: "robinhood#dividends"
  get "documents", to: "robinhood#documents"
  get "price_chart", to: "robinhood#price_chart"
  get "api", to: "robinhood#api"
  get "experiments", to: "robinhood#experiments"

  get "positions", to: "robinhood#positions"
  post "reorder_positions", to: "robinhood#reorder_positions"

  get "transfers", to: "robinhood#transfers"
  post "new_transfer", to: "robinhood#new_transfer"
  get "cancel_transfer", to: "robinhood#cancel_transfer"

  get "cards", to: "robinhood#cards"
  get "dismiss_card", to: "robinhood#dismiss_card"
  get "dismiss_all_cards", to: "robinhood#dismiss_all_cards"

  post "add_to_watchlist", to: "robinhood#add_to_watchlist"
  post "remove_from_watchlist", to: "robinhood#remove_from_watchlist"
  post "create_watchlist", to: "robinhood#create_watchlist"
  get "watchlist", to: "robinhood#watchlist"

  get "orders", to: "robinhood#orders"
  post "new_order", to: "robinhood#new_order"
  get "cancel_order", to: "robinhood#cancel_order"

  get "delete_stock_list", to: "robinhood#delete_stock_list"
  post "add_stock_list", to: "robinhood#add_stock_list"

  # crypto
  get "crypto_watchlist", to: "robinhood#crypto_watchlist"
end

app/controllers/robinhood_controller.rb
class RobinhoodController < ApplicationController
  include Robinhood
  include FinanceCalculator

  #before_filter :set_oauth_token, except: [:login, :logout]

  def login
    if params[:challenge_code].present?
      success = complete_challenge params[:challenge_code]
      session[:robinhood_device_token] = nil unless success
    end
    response = set_account_token params[:username], params[:password], params[:security_code]
    
    if response["mfa_required"] || response["accept_challenge_types"]
      flash[:info] = "Please provide the security code that was sent via text."
      flash[:password] = params[:password]
      flash[:username] = params[:username]
    end
    flash[:warning] = response["non_field_errors"].join if response["non_field_errors"].present?
    redirect_to root_path(mfa_required: response["mfa_required"], challenge_required: response["accept_challenge_types"].present?)
  end

  def logout
    reset_session
    @current_user = nil
    redirect_to root_path
  end

  def markets
    get_markets
    render layout: false
  end

  def dividends
    get_dividends
    @dividends.each do |dividend|
      dividend["instrument"] = robinhood_get dividend["instrument"]
    end
  end

  def documents
    get_documents
  end

  def fundamentals
    get_fundamentals params["symbols"].split(",")
    @fundamentals.each do |symbol,data|
      data["earnings"] = next_earnings_report symbol
    end
    render layout: false
  end

  def price_chart
    if params[:type] =~ /portfolio/i
      @chart_data = portfolio_line_chart params[:interval], {span: params[:span]}
    elsif params[:type] =~ /stock/i
      @chart_data = stock_line_chart params[:symbol], params[:interval], {span: params[:span]}
    end
    render layout: false
  end
  
  def movers
    if params[:direction].present?
      @movers = get_sp500_movers(params[:direction])["results"]
    else
      @movers = get_sp500_movers("up")["results"]
      @movers += get_sp500_movers("down")["results"]
    end
    render layout: false
  end

  def cards
    get_cards
  end

  def dismiss_card
    success = dismiss_notification params["card_url"]
    if success
      flash[:success] = "Dismissed notification."
    else
      flash[:warning] = "Failed to dismiss notification."
    end
    redirect_to cards_path
  end

  def dismiss_all_cards
    get_cards
    success = true
    @cards.each do |card|
      success = success && dismiss_notification(card["url"])
    end
    if success
      flash[:success] = "Dismissed all notifications."
    else
      flash[:warning] = "Failed to dismiss notifications."
    end
    redirect_to root_path
  end

  def news
    get_news params[:symbol]
  end

  def history
    get_history params[:symbol].upcase, params[:interval].downcase, {span: params[:span].downcase}
    render layout: false
  end

  def quote
    if params["symbols"].present?
      @side = params[:side] || "buy"
      begin
        if @side =~ /buy/i
          get_accounts
        else
          positions
        end
        get_quotes params["symbols"].upcase
        @quotes.delete_if{|q| q.nil?}
      rescue Exception => e
        if(!@quotes || @quotes.empty?)
          get_instruments params["symbols"].upcase
          @quotes = @instruments.map{|instrument| robinhood_get instrument["quote"]}
        end
      ensure
        @quotes ||= {}
      end
    else
      @quotes = {}
    end
    crypto_quote
  end

  def crypto_quote
    if params["symbols"].present?
      @side = params[:side] || "buy"
      if @side =~ /buy/i
        pairs = []
        get_crypto_pairs.each do |pair|
          asset_currency = pair["asset_currency"]
          if asset_currency["code"] =~ /#{params["symbols"]}/i || asset_currency["name"] =~ /#{params["symbols"]}/i
            pairs << pair
          end
        end
        @crypto_quotes = get_crypto_pair_quotes(pairs.map{|p| p["id"]}) || []
        @crypto_quotes.each do |quote|
          quote["pair"] = pairs.find{|pair| pair["id"] == quote["id"] }
        end
      end
    end
  end

  def transfers
    get_transfers
    get_ach_accounts
  end

  def new_transfer
    response = robinhood_post "https://api.robinhood.com/ach/transfers/", {direction: params[:direction].downcase, amount: params[:amount], ach_relationship: params[:ach_relationship]}
    success = response["id"].present?
    if success
      flash[:success] = "Successfully created transfer."
    else
      flash[:warning] = response.values.join
    end
    redirect_to transfers_path
  end

  def cancel_transfer
    response = robinhood_post params["transfer_url"], {}
    success = response.empty?
    if success
      flash[:success] = "Successfully canceled transfer."
    else
      flash[:warning] = "Failed to cancel transfer: #{response.values.join}"
    end

    redirect_to transfers_path
  end

  def portfolios
    get_accounts
    get_markets
    get_portfolios

    market = @markets.first
    @market_open = DateTime.parse(market["opens_at"]) if market["opens_at"].present?
    @market_open = @market_open && @market_open < Time.now && DateTime.parse(market["closes_at"]) > Time.now
    # instant accounts use margin_balances. cash just uses buying power
    @buying_power = @accounts.map{|a| a["margin_balances"].present? ? a["margin_balances"]["overnight_buying_power"] : a["buying_power"]}.sum

    render layout: false
  end

  def portfolio_history
    account = current_user.main_account.account_number
    get_portfolio_history account, params[:interval], {span: params[:span]}
    raise @portfolio_history.to_s
  end

  def positions
    @investments = {}
    @instruments = []
    get_positions
    @positions.each do |position|
      instrument = find_or_create_instrument position["instrument"]
      @instruments << instrument
      position["instrument"] = instrument
      @investments[instrument["symbol"]] = position
    end

    get_quotes @investments.keys
    @quotes.each do |quote|
      quote.delete "instrument" # we already have it
      @investments[quote["symbol"]].merge! quote
    end

    get_orders
    @investments.each do |symbol,data|
      data["all_time_return"] =  0.0 # return including sold shares
      data["purchase_cost"] = 0.0
      data["amount_sold"] = 0.0
      data["todays_return"] = 0.0
      data["current_price"] = (data["last_extended_hours_trade_price"] || data["last_trade_price"]).to_f
      instrument_orders = @orders.select{|o| o["instrument"] == data["instrument"].url && !o["executions"].empty?}
      buy_orders = instrument_orders.select{|o| o["side"] =~ /buy/i}
      sell_orders = instrument_orders - buy_orders
      total_num_shares_to_skip = sell_orders.map{|o| o["executions"].map{|e| e["quantity"].to_i}.sum }.sum

      get_splits data["instrument"].robinhood_id
      @splits.each{|split| split["updated_at"] = split["execution_date"]}
      current_shares_owned = 0
      # process orders oldest to newest
      orders_and_splits = (instrument_orders + @splits).sort{|a,b| DateTime.parse(a["updated_at"]) <=> DateTime.parse(b["updated_at"])}
      orders_and_splits.each do |o|
        if o["url"] =~ /order/i
          price = (o["average_price"] || o["price"]).to_f
          quantity = o["executions"].map{|e| e["quantity"].to_i}.sum
          if o["side"] =~ /buy/i
            data["purchase_cost"] += price * quantity
            current_shares_owned += quantity
          else
            data["amount_sold"] += (price * quantity - o["fees"].to_f)
            current_shares_owned -= quantity
          end
        else 
          # split
          current_shares_owned = (current_shares_owned / o["divisor"].to_f * o["multiplier"].to_f).to_i
        end
      end
      # TODO: this quantity override doesnt seem to work for stocks received for free (like through the referral program)
      #data["quantity"] = current_shares_owned # override quantity from robinhood

      # calculate todays return (basically check if anything was bought today)
      todays_buy_orders = buy_orders.select{|o| o["executions"].any?{|e| DateTime.parse(e["timestamp"]) > Date.today}}
      todays_buy_orders.each do |o|
        price = (o["average_price"] || o["price"]).to_f
        o["executions"].each do |e|
          executed_shares = e["quantity"].to_i
          current_shares_owned -= executed_shares
          # check if user bought some shares then sold them
          # example: buy 2 shares, sell 1 share in same day
          executed_shares += current_shares_owned if current_shares_owned < 0
          data["todays_return"] += (data["current_price"] - price) * executed_shares
        end
      end
      data["todays_return"] += (data["current_price"] - data["previous_close"].to_f) * current_shares_owned if current_shares_owned > 0

      data["value"] = data["quantity"].to_i * data["current_price"]
      data["shares_held_cost"] = data["average_buy_price"].to_f * data["quantity"].to_i
      data["shares_held_return"] = data["value"] - data["shares_held_cost"]
      data["all_time_return"] = data["value"] - data["purchase_cost"] + data["amount_sold"]
    end

    # remove investments where we no longer hold any shares
    @investments.delete_if{|symbol,data| data["quantity"].to_i <= 0}

    @stock_lists = current_user.update_stock_list :portfolio, @instruments
    @stock_lists = @stock_lists.sort{|a,b| a.name.nil? ? 0 : 1}
    
    render layout: false
  end

  def delete_stock_list
    current_user.stock_lists.find(params[:id]).try(:delete)
    render nothing: true
  end

  def add_stock_list
    current_user.main_account.stock_lists.create! group: params[:group], name: params[:name]
    flash[:success] = "Added section."
    redirect_to root_path
  end

  def reorder_positions
    instrument_order = Instrument.find(params[:instrument_order])
    list = current_user.stock_lists.find params[:id]
    if list.present?
      robinhood_instruments = Instrument.find(params[:robinhood_order]).pluck(:robinhood_id)

app/helpers/robinhood_helper.rb
module RobinhoodHelper
end

app/views/robinhood/_crypto_quote.html.haml
- return if quote.nil?
- price = quote["mark_price"]
- instrument ||= nil
%tr.watchlist-item.fundamentals-tooltip{class: "watchlist-hide-#{instrument.try(:id)}", data: { instrument_id: instrument.try(:id)}}
  %td= crypto_link(from_pair, {class: "symbol", data:{ html: true, placement: :right}})
  %td= to_pair =~ /us\s*dollar/i ? to_pair.titleize.pluralize : crypto_link(to_pair, {class: "symbol", data:{ html: true, placement: :right}})
  %td= price_display price
  %td.change{class: "text-" + up_down(quote["open_price"], price)}
    = change_display(quote["open_price"], price)
  %td= "TODO" #render "robinhood/order_form_modal", symbol: instrument.symbol, side: @side, price: price, num_shares: (@investments.present? ? @investments[instrument.symbol]["quantity"] : nil)
  - if instrument.present?
    %td.remove-from-watchlist
      = form_tag remove_from_watchlist_path, remote: true do
        = hidden_field_tag :robinhood_id, instrument.robinhood_id
        = hidden_field_tag :watchlist_id, list.id
        = submit_tag "X", class: "btn btn-default hide-on-click", data: {target: ".watchlist-hide-#{instrument.id}"}
  - else
    %td.add-to-watchlist
      = form_tag add_to_watchlist_path do
        = hidden_field_tag :robinhood_id, quote["id"]
        = hidden_field_tag :type, :crypto
        = submit_tag "+", class: "btn btn-default"

app/views/robinhood/_order.html.haml
- price = order["average_price"] || order["price"]
- type = "Market" if order["trigger"] == "immediate" && order["type"] == "market"
- type = "Limit" if order["trigger"] == "immediate" && order["type"] == "limit"
- type = "Stop loss" if order["trigger"] == "stop" && order["type"] == "market"
- type = "Stop limit" if order["trigger"] == "stop" && order["type"] == "limit"
.order.fundamentals-tooltip
  %h3= stock_link order["instrument"]["symbol"], {class: "symbol", data: {html: true, placement: :right}}
  .total
    = price_display(order["quantity"].to_i * price.to_f)
  .type= "#{type} #{order["side"]}"
  .order-date= DateTime.parse(order["updated_at"]).in_time_zone(user_timezone).strftime("%b %e %Y %l:%M%P")
  .expected-date= "Expected " + order["executions"].first["settlement_date"] if order["side"] =~ /sell/i && !order["executions"].empty?
  .price
    - if price.present?
      = price_display price
      per share
  .stop_price
    - if order["stop_price"].present?
      = price_display order["stop_price"]
      stop
  .quantity
    = order["filled_quantity"] + " / " + order["quantity"].to_i.to_s
    = "Share".pluralize(order["quantity"].to_i)
  .status{class: order["state"] =~ /^filled/i ? "text-success" : "text-danger"}
    = order["state"].capitalize.sub("_", " ")
  .fees
    = price_display order["fees"]
    fee
  .cancel
    = link_to "Cancel", cancel_order_path(url: order["cancel"]) if order["cancel"].present?

  - if false # debug
    .col-xs-12
      = order

app/views/robinhood/_order_form_modal.html.haml
- target = "#{side}#{symbol.gsub('.','')}"
.stop-deferred-loader= link_to side.capitalize, "#", data: {toggle: :modal, target: ".#{target}"}, class: "btn btn-default"

.modal.fade{role: "dialog", tabindex: "-1", class: target}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %h4.modal-title #{side.capitalize} #{symbol}

      #order-form{data: {behavior: "OrderForm", side: side, price: set_num_decimals(price, delimiter: '')}, class: "order_form_#{target}"}
        = form_tag new_order_path, class: "form-inline" do
          = hidden_field_tag :symbol, symbol
          = hidden_field_tag :side, side

          .modal-body
            .row
              .col-xs-12
                %h5 Current price per share: #{price_display price}
            %br
            .row
              .col-xs-3
                .form-group
                  = label_tag "Order type"
                  = select_tag :type, options_for_select(["Market", "Limit", "Stop loss", "Stop limit"]), class: "form-control"
              .col-xs-9
                %p.order-description

            %br
            .row
              .col-xs-6
                .form-group
                  = label_tag "Number of shares"
                  = number_field_tag :quantity, 1, min: 1, class: "form-control"
              .col-xs-6
                .form-group
                  = label_tag "Price"
                  = number_field_tag :price, set_num_decimals(price, delimiter: ''), step: 0.01, min: 0.01, class: "form-control"
                  .market-placeholder
                    Best available
            %br
            .row
              .col-xs-6
                .form-group
                  = label_tag "Time in force"
                  = select_tag :time_in_force, options_for_select([ ["Good for day", "gfd"], ["Good til canceled", "gtc"] ]), class: "form-control"
              .col-xs-6
                .form-group
                  = label_tag "Stop price"
                  = number_field_tag :stop_price, set_num_decimals(price, delimiter: ''), step: 0.01, min: 0.01, class: "form-control"               

          .modal-footer
            %button.btn.btn-danger{"data-dismiss" => "modal", :type => "button"} Cancel
            = submit_tag "Place order", class: "btn btn-success", data: {confirm: "Are you sure you want to #{side} #{symbol}?"}

app/views/robinhood/_quote_form.html.haml
#quote-form
  = form_tag quote_path, method: :get do
    .form-group
      = text_field_tag :symbols, nil, placeholder: "Search stock or name", class: "form-control"
      %span.fa.fa-search
    = submit_tag "Get quote", class: "btn btn-default"

app/views/robinhood/_stock_list_form.html.haml
= form_tag add_stock_list_path, class: "form-inline" do
  = hidden_field_tag :group, group
  .form-group
    = text_field_tag :name, nil, placeholder: "Add a section folder", class: "form-control", required: true
  = submit_tag "Add section", class: "hidden"

app/views/robinhood/_transfer_form.html.haml
= form_tag new_transfer_path do
  .form-group
    = label_tag "Account"
    - options = accounts.select{|a| a["verified"]}.map{|a| [a["bank_account_nickname"], a["url"]]}
    = select_tag :ach_relationship, options_for_select(options), class: "form-control"
  .form-group
    = label_tag "Type"
    = select_tag :direction, options_for_select(["Deposit", "Withdraw"]), class: "form-control"
  .form_group
    = label_tag "Amount"
    = number_field_tag :amount, 1, min: 1, class: "form-control"
  %br
  = submit_tag "Submit", class: "btn btn-success"

app/views/robinhood/api.html.haml
.col-xs-10
  %h2 API Explorer
  - if @user.blank?
    %h4= link_to "< Back", "javascript: history.go(-1);"
  - if @user.present?
    = render "layouts/hash_display", data: @user
    .col-xs-4.col-sm-3
      = link_to "Experiments", experiments_path

  = render "layouts/hash_display", data: @data
  
  .col-xs-12
    %br
    %h3 Custom API URL
    = form_tag api_path, method: :get do
      .form-group
        .col-xs-3
          = text_field_tag :url, @url, class: 'form-control'
        = submit_tag 'Submit', class: 'btn btn-primary'

app/views/robinhood/cards.html.haml
.col-xs-10
  %h2 Notifications
  = link_to "Dismiss all", dismiss_all_cards_path, class: "btn btn-default"
  %br
  - @cards.each do |card|
    .col-sm-4
      .card
        %h3= card["title"]
        - if card["time"].present?
          = DateTime.parse(card["time"]).in_time_zone(user_timezone).strftime("%b %e %Y %l:%M%P")
          %br
        = card["message"]
        %br
        - if card["action"].present? && card["action"] =~ /url=(.+)/
          = link_to "Read more", URI.unescape($1), target: "_blank"
          %br
        = link_to "Dismiss", dismiss_card_path(card_url: card["url"])
  - if @cards.empty?
    .col-xs-12
      %br
      %p It looks like you don't have any notifications.

app/views/robinhood/history.html.haml
- if @history.present?
  - @history.each do |h|
    = h
- else
  %p Couldn't find any history.

app/views/robinhood/movers.html.haml
- @movers.each do |mover|
  = mover["symbol"] rescue raise mover.to_s
  = mover["price_movement"]["market_hours_last_movement_pct"]
  = mover["price_movement"]["market_hours_last_price"]
  %br

app/views/robinhood/new_order.html.haml
= @order

app/views/robinhood/orders.html.haml
.col-xs-10{data: {behavior: "FundamentalsTooltip"}}
  %h2 Orders

  %ul.nav.nav-tabs{data: {behavior: "SubMenu"}}
    %li.active{role: "presentation"}
      = link_to "All", "#", data: {target: ".first-tab"}
    %li{role: "presentation"}
      = link_to "Buy", "#", data: {target: ".second-tab"}
    %li{role: "presentation"}
      = link_to "Sell", "#", data: {target: ".third-tab"}
    %li{role: "presentation"}
      = link_to "Filled", "#", data: {target: ".fourth-tab"}
    %li{role: "presentation"}
      = link_to "Unfilled", "#", data: {target: ".fifth-tab"}
    %li{role: "presentation"}
      = link_to "Cancelled", "#", data: {target: ".sixth-tab"}

  .first-tab.sub-menu-tab
    - @orders.each do |order|
      .col-xs-4.col-sm-3
        = render "order", order: order
  .second-tab.sub-menu-tab
    - @orders.select{|o| o["side"] =~ /buy/i}.each do |order|
      .col-xs-4.col-sm-3
        = render "order", order: order
  .third-tab.sub-menu-tab
    - @orders.select{|o| o["side"] =~ /sell/i}.each do |order|
      .col-xs-4.col-sm-3
        = render "order", order: order
  .fourth-tab.sub-menu-tab
    - @orders.select{|o| !o["executions"].empty?}.each do |order|
      .col-xs-4.col-sm-3
        = render "order", order: order
  .fifth-tab.sub-menu-tab
    - @orders.select{|o| o["state"] !~ /(filled|cancelled)/i}.each do |order|
      .col-xs-4.col-sm-3
        = render "order", order: order
  .sixth-tab.sub-menu-tab
    - @orders.select{|o| o["state"] =~ /cancelled/i}.each do |order|
      .col-xs-4.col-sm-3
        = render "order", order: order


  = javascript_include_tag "https://www.gstatic.com/charts/loader.js"

app/views/robinhood/price_chart.html.haml
.col-xs-12
  - target = SecureRandom.hex(4)
  .price-chart{data: {behavior: "LineChart", chart: @chart_data.to_json, target: ".#{target}"}}
    .chart-placeholder{class: target}

app/views/robinhood/transfers.html.haml
- unlinked_accounts = @ach_accounts.select{|a| a["unlinked_at"].nil?}
.col-xs-10
  %h2 ACH transfers and accounts
  .col-sm-4.col-xs-6
    = link_to "Create a new transfer", "#transfer-form", "data-toggle": :collapse, "aria-controls": "#transfer-form", "aria-expanded": false, class: "btn btn-default"
    #transfer-form.collapse
      %br
      = render "robinhood/transfer_form", accounts: @ach_accounts
      %br
      %br


  %br
  %br
  %br
  .col-xs-12
    %ul.nav.nav-tabs{data: {behavior: "SubMenu"}}
      - unlinked_accounts.each_with_index do |account,i|
        %li{role: "presentation", class: (i == 0 ? "active" : "")}
          = link_to account["bank_account_nickname"] + " " + account["bank_account_type"].capitalize, "#", data: {target: ".tab-#{i}"}

    - unlinked_accounts.each_with_index do |account,i|
      .col-xs-12.sub-menu-tab{class: "tab-#{i}"}
        %h3= account["verified"] ? "Verified" : "Unverified"
        - if false # debug
          = account

        - @transfers.select{|t| t["ach_relationship"] == account["url"]}.each do |transfer|
          - state = transfer["state"].capitalize
          - direction = transfer["direction"].capitalize
          - amount = transfer["amount"]
          - complete = state =~ /complete/i
          - amount_available = complete ? amount : transfer["early_access_amount"]
          .col-xs-4.transfer
            %h3{class: direction =~ /deposit/i ? "text-success" : "text-danger"}= price_display amount
            #{state} #{direction}
            %br
            #{price_display amount_available} of #{price_display amount} available
            %br
            Expected
            = transfer["expected_landing_date"]
            %br
            - if transfer["cancel"].present?
              = link_to "Cancel", cancel_transfer_path(transfer_url: transfer["cancel"]), data: {confirm: "Are you sure you want to cancel this transfer?"}

            - if false # debug
              = transfer